// Celestial Incremental 汉化 - 运行时翻译词典
// 用于翻译既是键名又是显示文本的条目
var cnItems = {
    // === 通用标签 ===
    "Upgrades": "升级",
    "Milestones": "里程碑",
    "Challenges": "挑战",
    "Buyables": "可购买",
    "Clickables": "可点击",
    "Main": "主要",
    "Info": "信息",
    "Stats": "统计",
    "General": "通用",
    "Advanced": "高级",
    "Special": "特殊",
    "Other": "其他",
    "Normal": "普通",
    "Regular": "常规",
    "Secret": "秘密",
    "Hidden": "隐藏",
    "Bonus": "奖励",
    "Effects": "效果",
    "Unlocks": "解锁",
    "Perks": "特权",
    "Pets": "宠物",
    "Ships": "飞船",
    "Skills": "技能",
    "Battle": "战斗",
    "Shop": "商店",
    "Options": "选项",
    "Sounds": "音效",
    "Music": "音乐",
    "Cost": "消耗",
    "Req": "需求",
    "Gain": "获得",
    "Reward": "奖励",
    "Progress": "进度",
};
